import { Article } from '@/types'

export const articles: Article[] = [
  // CHAPTER 0: Before You Begin
  {
    id: '0-1',
    slug: 'about-the-author',
    title: 'About the Author: Shri Chidambaranathan',
    content: 'My name is Shri Chidambaranathan, and welcome to The Science Fair Guidebook! I am a member of Washburn Rural\'s Class of 2027 with a strong passion for scientific research. I have attended numerous conferences, presented posters, and published research. Research has been one of the most rewarding experiences of my high school career because of the skills I have developed, the people I have met, and the opportunities it has opened for me. After attending the 2026 International Science and Engineering Fair (ISEF), I was inspired by the community and made it my mission to make the scientific research process more accessible to everyone and a little less daunting. I competed in the Computational Biology and Bioinformatics division with research on "In Silico Modeling of Bispecific Dual-Affinity Re-Targeting (DART) Molecules Targeting PD-1 and LAG-3 for Solid Tumor and Hematologic Cancer Immunotherapy." If you have any questions, feel free to reach out via email or LinkedIn.',
    stage: 'planning',
    category: 'Getting Started',
    author: 'Shri Chidambaranathan',
    read_time: 4,
    word_count: 180,
    featured: true,
    created_at: '2024-01-01T00:00:00Z',
    updated_at: '2024-01-01T00:00:00Z',
    related_articles: ['about-this-guide'],
  },
  {
    id: '0-2',
    slug: 'about-this-guide',
    title: 'About This Guide: How to Use It',
    content: 'When I started my science fair journey, I had more questions than answers. I learned through trial and error, countless hours of research, and plenty of mistakes along the way. This guide is designed to help you navigate every stage of the research process with confidence. Whether you\'re preparing for your first science fair or aiming for ISEF, you\'ll learn how to develop the mindset of a researcher, find and refine original ideas, read scientific literature, design rigorous experiments, stay organized, write research papers, create posters, and continue your work beyond the fair. This guide follows the complete research journey from your first idea to presenting your work. You can read it in order, with each chapter building on the last, or revisit individual sections whenever you need guidance. Along the way, you\'ll find examples, common mistakes to avoid, checklists, and practical advice.',
    stage: 'planning',
    category: 'Getting Started',
    author: 'Shri Chidambaranathan',
    read_time: 5,
    word_count: 190,
    featured: true,
    created_at: '2024-01-02T00:00:00Z',
    updated_at: '2024-01-02T00:00:00Z',
    related_articles: ['about-the-author'],
  },

  // CHAPTER 1: Getting Started
  {
    id: '1-1-a',
    slug: 'why-science-fair-skills',
    title: 'Why Science Fair? Skills You\'ll Gain',
    content: 'The scientific research process has been the most transformative experience. Beyond expected skills like conducting research, scientific writing, data analysis, and subject-specific knowledge, you\'ll develop countless unexpected skills. It improves your public speaking, graphic design, communication, argumentation, organization, proactivity, perseverance, time management, compartmentalization, and ability to work under pressure. These skills benefit you in every aspect of your life, both inside and outside science fairs. Research teaches you how to think critically, adapt to challenges, and communicate your ideas clearly.',
    stage: 'planning',
    category: 'Mindset',
    author: 'Shri Chidambaranathan',
    read_time: 3,
    word_count: 140,
    featured: true,
    created_at: '2024-01-03T00:00:00Z',
    updated_at: '2024-01-03T00:00:00Z',
    related_articles: ['why-science-fair-impact', 'why-science-fair-network'],
  },
  {
    id: '1-1-b',
    slug: 'why-science-fair-impact',
    title: 'Why Science Fair? Making Real Impact',
    content: 'Science fairs provide an excellent forum for sharing your ideas and creating real value in your community. They give you an opportunity to showcase months or even years of hard work while receiving thoughtful feedback from experts who can help strengthen your research. Many students view science fairs as the finish line of their project, but they\'re actually the beginning. Science fairs are an opportunity to share your findings, spark conversations, inspire others, and contribute to solving real problems. Instead of your project sitting on a shelf, your work reaches an audience that genuinely wants to learn from it and help improve it.',
    stage: 'planning',
    category: 'Impact',
    author: 'Shri Chidambaranathan',
    read_time: 3,
    word_count: 155,
    featured: false,
    created_at: '2024-01-04T00:00:00Z',
    updated_at: '2024-01-04T00:00:00Z',
    related_articles: ['why-science-fair-skills', 'why-science-fair-network'],
  },
  {
    id: '1-1-c',
    slug: 'why-science-fair-network',
    title: 'Why Science Fair? Build Your Network',
    content: 'One of the greatest things you\'ll gain from science fairs is not the awards—it\'s the people. Science fairs place you in a community of curious, motivated individuals who genuinely want to learn from one another. Whether you are exchanging ideas, celebrating successes, or helping each other through setbacks, you\'re surrounded by people who push you to grow both as a researcher and as a person. ISEF, in particular, shows that science truly is a universal language. Students from all over the world share the same curiosity and excitement for discovery. The number of students, researchers, professors, and professionals you\'ll meet who share similar interests is astounding.',
    stage: 'planning',
    category: 'Community',
    author: 'Shri Chidambaranathan',
    read_time: 3,
    word_count: 165,
    featured: false,
    created_at: '2024-01-05T00:00:00Z',
    updated_at: '2024-01-05T00:00:00Z',
    related_articles: ['why-science-fair-skills', 'why-science-fair-impact'],
  },
  {
    id: '1-2',
    slug: 'research-mindset',
    title: 'The Research Mindset: Growth, Failure & Iteration',
    content: 'The biggest thing to remember is that you do not have to be a genius to succeed at science fairs. You simply need the right mindset. Prioritize growth over awards—focus on the knowledge, skills, and personal growth you\'ll gain, not just winning. Embrace failure as every researcher encounters setbacks; experiments fail, hypotheses fall apart. Every setback is an opportunity to learn, adapt, and build perseverance. Welcome rejection—actively seek it. Rejection is inevitable but remember it only takes one "yes." Never settle—your project is never truly finished. Continue refining your methodology, strengthening your analysis, improving your poster. Seek feedback often and use it. Track your progress by keeping a record of milestones and improvements. Measure your accomplishments regularly to stay motivated.',
    stage: 'planning',
    category: 'Mindset',
    author: 'Shri Chidambaranathan',
    read_time: 4,
    word_count: 195,
    featured: true,
    created_at: '2024-01-06T00:00:00Z',
    updated_at: '2024-01-06T00:00:00Z',
    related_articles: ['competition-pathway'],
  },
  {
    id: '1-3',
    slug: 'competition-pathway',
    title: 'The Competition Pathway: From Local to ISEF',
    content: 'The pathway to the Regeneron International Science and Engineering Fair (ISEF) is a multi-tiered competition system. You cannot apply directly to ISEF; you must advance through the Society for Science Affiliated Fair Network. The pathway includes: School/Local Fairs (optional, for practice), Regional Affiliated Fairs (mandatory), and State/National Fairs (if offered, for final advancement). Basic eligibility: grades 9-12, not turned 20 by May 1 of competition year, individual or team projects (max 3 members), and 12 months of continuous research. The competition timeline spans summer/fall (begin research), winter/spring (defend research at fairs), and April (if selected, travel to ISEF). Each affiliated fair has a strict quota; approximately 0.03% of participants qualify for ISEF.',
    stage: 'planning',
    category: 'Competition',
    author: 'Shri Chidambaranathan',
    read_time: 4,
    word_count: 180,
    featured: true,
    created_at: '2024-01-07T00:00:00Z',
    updated_at: '2024-01-07T00:00:00Z',
    related_articles: ['research-mindset'],
  },

  // CHAPTER 2: Finding Your Idea
  {
    id: '2-1',
    slug: 'where-good-ideas-come-from',
    title: 'Where Good Ideas Come From: Six Places to Look',
    content: 'Every great project starts with a single spark. The best ideas come from curiosity, observation, and asking "what if?" Six places to find ideas: (1) Your Surroundings—look at problems in your school, community, home. What frustrates you? What could be improved? (2) Current Events—stay informed about global challenges, new technologies, and scientific breakthroughs. (3) Your Passions—your interests and hobbies can lead to meaningful research. (4) Other People—conversations with teachers, mentors, experts, and peers spark ideas you wouldn\'t have alone. (5) Read and Explore—dive into scientific journals and resources. The more you learn, the more questions arise. (6) Past Research—what are the limitations of existing studies? What can be expanded or tested in new ways? The best ideas combine observations, staying informed, asking questions, exploring research, and identifying gaps in knowledge.',
    stage: 'research',
    category: 'Ideation',
    author: 'Shri Chidambaranathan',
    read_time: 5,
    word_count: 240,
    featured: true,
    created_at: '2024-01-08T00:00:00Z',
    updated_at: '2024-01-08T00:00:00Z',
    related_articles: ['evaluating-an-idea', 'reading-scientific-papers'],
  },
  {
    id: '2-2',
    slug: 'evaluating-an-idea',
    title: 'Evaluating Your Idea: Six Critical Criteria',
    content: 'Evaluate before investing months of work. A quick screening can save you time and help you focus on ideas that are meaningful and feasible. Interest: Is it interesting to me? You may spend months on this; choose something you care about. Originality: Is it original enough? Your project doesn\'t need to be completely unique, but it should add something new or investigate a question differently. Feasibility: Is it feasible? Consider time, equipment, materials, and access to data. If not feasible, narrow the scope. Measurability: Can you collect data and test your idea? Good research questions lead to measurable observations, experiments, surveys, or analyses. Impact: Why does this matter? The strongest projects connect their question to a real scientific, engineering, medical, environmental, or social problem. Ethicality: Is it safe and ethical? Projects involving humans, animals, pathogens, or hazardous materials may require additional approvals.',
    stage: 'research',
    category: 'Planning',
    author: 'Shri Chidambaranathan',
    read_time: 4,
    word_count: 225,
    featured: true,
    created_at: '2024-01-09T00:00:00Z',
    updated_at: '2024-01-09T00:00:00Z',
    related_articles: ['where-good-ideas-come-from', 'reading-scientific-papers'],
  },
  {
    id: '2-3',
    slug: 'reading-scientific-papers',
    title: 'How to Read Scientific Papers Efficiently',
    content: 'After finding your idea, read scientific research to provide the basis for your project. This matters because: (1) Find open questions and see exactly what gaps exist in current research. (2) Steal proven methods—don\'t guess how to run your test; copy the exact procedures professionals use. (3) Avoid repetition by ensuring your idea hasn\'t already been done. (4) Build credibility by citing real studies; judges will see your project is backed by solid science. Scientific papers are dense; don\'t read them start to finish. Instead: (1) Read the Abstract first—this 200-word summary tells you if the paper is relevant. (2) Read the Conclusion next—find out what scientists actually discovered before getting bogged down in data. (3) Read the Introduction to understand background history and why the topic matters. (4) Dive into Methods & Results last only if you plan to replicate or modify their experiment.',
    stage: 'research',
    category: 'Research',
    author: 'Shri Chidambaranathan',
    read_time: 4,
    word_count: 235,
    featured: false,
    created_at: '2024-01-10T00:00:00Z',
    updated_at: '2024-01-10T00:00:00Z',
    related_articles: ['where-good-ideas-come-from', 'literature-review-basics'],
  },
  {
    id: '2-4',
    slug: 'literature-review-basics',
    title: 'Literature Review: Organizing Existing Research',
    content: 'A literature review is a summary and analysis of existing research related to your topic. It helps you understand what is already known and where your project fits. Steps: (1) Gather Sources—start broad, then narrow down. This helps you accumulate basic knowledge while focusing on your specific topic. Add links to papers/websites to a document to stay organized. (2) Organize by Theme—group papers by topic instead of treating each as separate. Organizing by themes makes it easier to identify patterns and gaps. (3) Compare Findings—look for agreements, contradictions, and limitations across studies. These patterns often reveal opportunities for new research. Pay attention to outlined limitations; these could be starting points for your research. (4) Identify the Gap—ask yourself: What question remains unanswered? A strong research project addresses a meaningful gap in existing knowledge. (5) Connect to Your Project—explain how your research addresses the gap and why that matters. Common mistakes: reading papers one at a time, looking only for papers that support your idea. Science isn\'t about proving yourself right; contradictory results reveal the most interesting research questions.',
    stage: 'research',
    category: 'Research',
    author: 'Shri Chidambaranathan',
    read_time: 5,
    word_count: 280,
    featured: false,
    created_at: '2024-01-11T00:00:00Z',
    updated_at: '2024-01-11T00:00:00Z',
    related_articles: ['reading-scientific-papers', 'where-good-ideas-come-from'],
  },
  {
    id: '2-5',
    slug: 'research-tools',
    title: 'Helpful Research Tools: Connected Papers & ResearchRabbit',
    content: 'You don\'t have to conduct research alone. Connected Papers is a science mapping software tool excellent for literature review and identifying gaps. The Connected Papers graph shows: Node Size proportional to citation count (large nodes = influential papers), Node Darkness indicating recency (darker = more recent), Distance between nodes showing similarity, and Line Darkness indicating connection strength. By scanning the map for disconnected or isolated nodes, you can spot underexplored niches. ResearchRabbit is a visual literature mapping tool for academic research. It helps you discover, explore, and organize scholarly studies by mapping connections between articles, authors, and citations instead of relying on keyword searches. Features include: Interactive Nodes (each paper appears as a node; bigger nodes = more citations), Color-Coded Timelines (dots colored by publication year), Citation Webs (lines show "cited by" and "cites" relationships), Graph Layouts (timeline view organizes chronologically; network view groups by similarity), Author Networks (map co-authorship and collaboration), and Deep Dives (click on any node to read its abstract, view references, and spawn new graphs).',
    stage: 'research',
    category: 'Tools',
    author: 'Shri Chidambaranathan',
    read_time: 4,
    word_count: 245,
    featured: false,
    created_at: '2024-01-12T00:00:00Z',
    updated_at: '2024-01-12T00:00:00Z',
    related_articles: ['literature-review-basics', 'reading-scientific-papers'],
  },

  // CHAPTER 3: Designing Your Research
  {
    id: '3-1',
    slug: 'crafting-strong-research-question',
    title: 'Crafting a Strong Research Question',
    content: 'Your research question is the foundation of your entire project. It guides your methodology, shapes your analysis, and determines the impact of your findings. A strong question keeps your research focused and meaningful. Core qualities: FOCUSED—narrow enough to answer fully in your project scope. COMPLEX—requires deep thinking, investigation, or analysis; not a quick search. ARGUABLE—invites discussion and multiple possible outcomes. RESEARCHABLE—based on real data and evidence beyond personal opinion. Steps to draft: (1) Identify Your Variables—what am I changing (independent variable)? What am I measuring (dependent variable)? What am I keeping the same (controlled variables)? (2) Narrow Your Scope—most first drafts are far too broad. Make your question specific enough to investigate within one project. Example: "How does increasing polyethylene microplastic concentration in soil affect the growth rate and chlorophyll content of Arabidopsis thaliana over a four-week period?" (3) Refine and Evaluate—turn your idea into an open-ended question. Good research questions lead to measurable results.',
    stage: 'design',
    category: 'Methodology',
    author: 'Shri Chidambaranathan',
    read_time: 4,
    word_count: 250,
    featured: true,
    created_at: '2024-01-13T00:00:00Z',
    updated_at: '2024-01-13T00:00:00Z',
    related_articles: ['experimental-design', 'formulating-research-plan'],
  },
  {
    id: '3-2',
    slug: 'experimental-design',
    title: 'Experimental Design: Nine Methodologies Explained',
    content: 'Every project starts with an idea, question, or problem. The methodology you choose is simply the tool you use to find the answer. Nine design types: (1) EXPERIMENTAL RESEARCH—test cause-and-effect by changing one variable and measuring results in controlled lab environments. Example: testing microplastics concentration effects on radish seed germination. (2) ENGINEERING DESIGN—test hypotheses by changing one variable and measuring results. Example: different microplastic concentrations in soil affecting root length. (3) COMPUTER SCIENCE/CODING—write software, optimize algorithms, or train machine learning networks. Example: programming a custom neural network analyzing cough audio files to predict bronchitis. (4) THEORETICAL MATHEMATICS—use logic, formulas, and proofs to discover patterns or solve numerical puzzles. (5) OBSERVATIONAL STUDY—record and analyze natural behaviors/environmental patterns without interfering. Example: monitoring urban light pollution effects on nocturnal bat activity. (6) BEHAVIORAL & SOCIAL SCIENCE—study psychology, memory, and habits using ethical testing, surveys, or observation. Example: retention differences between physical textbooks and digital screens. (7) META-ANALYSIS & SYSTEMATIC REVIEW—combine data from dozens of published studies to find new trends. (8) SIMULATION & MODELING—create digital replicas of complex systems to test scenarios. Example: coastal town flooding predictions with different sea-wall heights. (9) PRODUCT TESTING—test and compare different commercial brands with strict, unbiased metrics.',
    stage: 'design',
    category: 'Methodology',
    author: 'Shri Chidambaranathan',
    read_time: 5,
    word_count: 300,
    featured: true,
    created_at: '2024-01-14T00:00:00Z',
    updated_at: '2024-01-14T00:00:00Z',
    related_articles: ['crafting-strong-research-question', 'finding-a-mentor'],
  },
  {
    id: '3-3',
    slug: 'finding-a-mentor',
    title: 'Finding a Mentor: Why, Where & How',
    content: 'A mentor can help you refine ideas, avoid common pitfalls, and see possibilities you might not have considered. Why a mentor is valuable: get expert feedback and advice, gain access to resources/equipment/lab experience, learn from their mistakes, open doors to future opportunities. However, a mentor is not required. Many award-winning projects are completed with determination, curiosity, and available resources alone. If finding a mentor proves difficult, don\'t let that stop you. Where to find mentors: (1) Teachers—science, math teachers who know your work ethic. (2) University Professors—look at university websites for faculty research areas; email professors whose work aligns with yours. (3) Researchers at Institutions—hospitals, labs, government agencies, nonprofits. (4) Science Fairs—judges, alumni, organizers become valuable contacts. (5) Online Communities—ResearchGate, LinkedIn, discipline-specific forums. (6) Personal Networks—don\'t underestimate family and extended networks. Email Tips: keep it brief and concise, research your prospect\'s work before reaching out, express genuine interest, don\'t immediately ask for months of mentorship; instead ask for advice, resources, or a 15-minute discussion. Follow Up: even if they can\'t help directly, keep the connection alive. Send polite follow-ups after weeks if you don\'t hear back. Once research is complete, send them a brief update or your final work. Many mentors appreciate seeing the impact and may remember you for future opportunities.',
    stage: 'design',
    category: 'Resources',
    author: 'Shri Chidambaranathan',
    read_time: 5,
    word_count: 310,
    featured: false,
    created_at: '2024-01-15T00:00:00Z',
    updated_at: '2024-01-15T00:00:00Z',
    related_articles: ['experimental-design', 'formulating-research-plan'],
  },
  {
    id: '3-4',
    slug: 'formulating-research-plan',
    title: 'Formulating a Research Plan: What to Include',
    content: 'ISEF requires: (1) The Research Plan is written prior to experimentation. (2) If changes are made during research before competing, add changes as an addendum to the original plan. Some changes may require IRB/SRC review before conducting that portion. Standard sections to include: RATIONALE—summarize the background supporting your question or goal. QUESTION, HYPOTHESIS, OR GOAL—state clearly and expected outcome. METHODS & PLAN—explain your approach including: materials, procedures/data collection, risks & safety precautions, data analysis. ACKNOWLEDGEMENTS—thank people who helped and describe their contributions. If AI was used, include a prompt log. BIBLIOGRAPHY—list major references in consistent citation style (APA, MLA, Chicago). Subject-specific additions: HUMAN PARTICIPANTS RESEARCH—describe participant demographics, recruitment, what they\'ll do, duration, risks and reduction strategies, privacy details, informed consent process. ANIMAL RESEARCH—justify why animals are needed, alternatives considered, procedures minimizing pain/stress, numbers/species/age/source, housing/daily care, post-study fate. BIOLOGICAL AGENTS—organism source, biosafety level, safety precautions, disposal methods. HAZARDOUS CHEMICALS/ACTIVITIES/DEVICES—risk assessment, safety measures, supervision, specific disposal, reference Safety Data Sheets (SDS). Check the official "Research Plan/Project Addendum" form for complete outline.',
    stage: 'design',
    category: 'Planning',
    author: 'Shri Chidambaranathan',
    read_time: 5,
    word_count: 280,
    featured: false,
    created_at: '2024-01-16T00:00:00Z',
    updated_at: '2024-01-16T00:00:00Z',
    related_articles: ['crafting-strong-research-question', 'finding-a-mentor'],
  },

  // CHAPTER 4: Conducting Your Research
  {
    id: '4-1',
    slug: 'lab-notebook-basics',
    title: 'Lab Notebook Basics: Keep Complete Records',
    content: 'Your lab notebook is your project\'s memory. It documents your procedures, observations, data, and decisions so you stay organized, troubleshoot problems, and reproduce results. Include: DATE—keeps work in chronological order, tracking project progress. PROJECT TITLE—states the experiment purpose clearly. OBJECTIVE—explains exactly what you\'re trying to accomplish. PROCEDURE—detailed enough for someone else to replicate your work. OBSERVATIONS—records qualitative details and unexpected events explaining later results. RAW DATA—preserves original measurements, ensuring transparent analysis. NEXT STEPS—outlines what should be completed for your next lab session. Example: "Date: October 3, 2026. Project: Testing Efficiency of Graphene Oxide Water Filters. Objective: Measure how graphene oxide coating thickness affects lead removal. Procedure: Prepared three filter membranes with varying coating thicknesses (0.5, 1.0, 1.5 mg/cm²). Passed 100 mL contaminated water through each. Observations: The 1.5 mg/cm² filter clogged after ~60 mL; repeated trial with new membrane. Raw Data: 0.5 mg/cm²=71% lead removed, 1.0 mg/cm²=86%, 1.5 mg/cm²=incomplete. Next Steps: Repeat final trial, calculate average removal efficiency." Record everything, including mistakes and unexpected outcomes.',
    stage: 'execution',
    category: 'Data Collection',
    author: 'Shri Chidambaranathan',
    read_time: 4,
    word_count: 250,
    featured: true,
    created_at: '2024-01-17T00:00:00Z',
    updated_at: '2024-01-17T00:00:00Z',
    related_articles: ['troubleshooting-pivoting', 'when-things-go-wrong'],
  },
  {
    id: '4-2',
    slug: 'troubleshooting-pivoting',
    title: 'Troubleshooting & Pivoting: When Things Don\'t Go as Planned',
    content: 'Every researcher encounters failed experiments, contradictory results, broken equipment, contaminated samples, and rejected hypotheses. What separates strong researchers isn\'t avoiding setbacks; it\'s knowing how to respond. IS IT TIME TO PIVOT? Ask: Can you identify the cause? If YES, fix the problem and repeat. If NO, read more literature, ask mentors/experts. Still not working? YES→Can the research question be narrowed/adjusted? YES→Pivot your methodology. NO→Consider a new direction. If your project goes exactly according to plan, you\'re probably doing something wrong. COMMON PROBLEMS: EXPERIMENT DOESN\'T WORK—don\'t panic. Ask: Did I follow procedure correctly? Were my controls appropriate? Is there equipment issue? Should I repeat? One failed trial isn\'t a failed experiment. RESULTS DON\'T SUPPORT HYPOTHESIS—Good! Research is discovering truth, not proving yourself right. Unexpected results often lead to most interesting discussions. LITERATURE CONTRADICTS FINDINGS—instead of assuming you\'re wrong, investigate why. Different methodology? population? sample size? assumptions? Differences become your discussion. RESOURCES UNAVAILABLE—look for alternative methods. Can you simulate it? Use public datasets? Simplify? Collaborate with another lab? Adapt before abandoning. YOU\'RE RUNNING OUT OF TIME—prioritize. Finish fewer experiments well instead of many poorly. Strong conclusions beat incomplete data every time.',
    stage: 'execution',
    category: 'Problem-Solving',
    author: 'Shri Chidambaranathan',
    read_time: 5,
    word_count: 310,
    featured: true,
    created_at: '2024-01-18T00:00:00Z',
    updated_at: '2024-01-18T00:00:00Z',
    related_articles: ['lab-notebook-basics', 'when-things-go-wrong'],
  },
  {
    id: '4-3',
    slug: 'when-things-go-wrong',
    title: 'If Things Go Wrong: Adapt, Learn, Move Forward',
    content: 'Research rarely follows a straight path. Ideas evolve, experiments fail, and unexpected results often lead to the best discoveries. The most important skill you\'ll develop is resilience—the ability to face setbacks, learn from them, and keep moving forward. Every failed experiment teaches you something. Every unexpected result is a clue. Every rejection is preparation for the next opportunity. Stay curious, trust the process, and enjoy the journey. Remember: research is built on trial and error, constant refinement, and problem-solving. The challenges you face now are the same challenges that researchers face worldwide. By learning how to overcome them, you\'re developing the mindset and skills that define great scientists. Your project is never truly finished. Continue refining your methodology, strengthening your analysis, improving your presentation. The most competitive projects are rarely the ones that started strongest—they\'re the ones that were improved over and over again. If this guidebook helps you take your first step into research or inspires you to pursue a project of your own, then it has accomplished exactly what I hoped it would.',
    stage: 'execution',
    category: 'Mindset',
    author: 'Shri Chidambaranathan',
    read_time: 4,
    word_count: 220,
    featured: false,
    created_at: '2024-01-19T00:00:00Z',
    updated_at: '2024-01-19T00:00:00Z',
    related_articles: ['troubleshooting-pivoting', 'lab-notebook-basics'],
  },

  // CHAPTER 5: Communicating Your Project
  {
    id: '5-1',
    slug: 'writing-research-paper',
    title: 'Writing a Research Paper: Structure & Tips',
    content: 'Your research paper tells the story of your project. It communicates your question, methods, results, and significance so others can understand, evaluate, and build upon your work. Standard sections: (1) ABSTRACT—brief summary of your entire paper (150-200 words). Write this last. (2) INTRODUCTION—introduce the problem, background, research gap, and objective. (3) METHODS—explain how you conducted research so it can be replicated. (4) RESULTS—present data clearly using tables, figures, and concise text. Don\'t interpret here. (5) DISCUSSION—interpret results, compare with existing research, acknowledge limitations, explain impact. (6) CONCLUSION—summarize findings and significance. What\'s next? (7) REFERENCES—list all sources you cited in proper format. Tips for strong papers: Be clear and concise; use simple, direct language. Stay organized with headings and subheadings. Use data to support claims; let results speak. Be objective; avoid personal opinions. Proofread carefully; grammar and clarity matter. Follow formatting guidelines; check competition requirements. CITATIONS: Use consistent style (APA, MLA, Chicago). Include authors, title, source, publication year, URL. BE CAUTIOUS WITH AI: AI tools can generate incorrect/fabricated citations. Always verify sources. It\'s acceptable to use AI as a writing assistant, not replacement for thinking.',
    stage: 'presentation',
    category: 'Communication',
    author: 'Shri Chidambaranathan',
    read_time: 5,
    word_count: 280,
    featured: true,
    created_at: '2024-01-20T00:00:00Z',
    updated_at: '2024-01-20T00:00:00Z',
    related_articles: ['designing-effective-poster'],
  },
  {
    id: '5-2',
    slug: 'designing-effective-poster',
    title: 'Designing an Effective Science Fair Poster',
    content: 'Your poster is your first impression and best way to connect with viewers. Judges have limited time per project, so communicate your story clearly and spark conversation. Steps: (1) PLAN BEFORE YOU DESIGN—write your key message in one sentence. What do you want judges to take away? Use this as your guide. Sketch a rough layout of sections on paper. (2) LOOK AT SUCCESSFUL EXAMPLES—get inspiration from past posters. What draws you? What makes it easy to read/understand? Use examples as starting point, not final product. Best posters communicate the essence of YOUR unique research. (3) ORGANIZE FOR FLOW—arrange sections logically: Introduction, Methods, Results, Conclusion, Discussion. Guide your reader\'s eyes top-left to bottom-right. Use arrows/numbering to make flow clear. (4) DESIGN FOR READABILITY—use bigger font for titles/headings, smaller for body text. Use high contrast. Don\'t use acronyms, complex language, or inaccessible vocabulary without explaining first. (5) VISUALIZE DATA STRATEGICALLY—use graphs, charts, photos, diagrams instead of paragraphs. Highlight the most important trend/result. Every figure should maintain your main message. (6) KEEP IT CONSISTENT & SIMPLE—use 2-3 main colors, consistent fonts, align everything. Clean edges look professional. Avoid decorative backgrounds and busy patterns. Before printing: double-check spelling/grammar, verify font size consistency, confirm poster is within size limits, verify all figures are labeled and titled.',
    stage: 'presentation',
    category: 'Communication',
    author: 'Shri Chidambaranathan',
    read_time: 4,
    word_count: 280,
    featured: true,
    created_at: '2024-01-21T00:00:00Z',
    updated_at: '2024-01-21T00:00:00Z',
    related_articles: ['writing-research-paper'],
  },
]

export function getArticles(): Article[] {
  return articles
}

export function getArticleBySlug(slug: string): Article | undefined {
  return articles.find(article => article.slug === slug)
}

export function getFeaturedArticles(): Article[] {
  return articles.filter(article => article.featured)
}

export function getArticlesByStage(stage: Article['stage']): Article[] {
  return articles.filter(article => article.stage === stage)
}

export function getArticlesByCategory(category: string): Article[] {
  return articles.filter(article => article.category === category)
}

export function searchArticles(query: string): Article[] {
  const lowerQuery = query.toLowerCase()
  return articles.filter(
    article =>
      article.title.toLowerCase().includes(lowerQuery) ||
      article.content.toLowerCase().includes(lowerQuery) ||
      article.category.toLowerCase().includes(lowerQuery)
  )
}
