import { Article } from '@/types'

export const articles: Article[] = [
  {
    id: '1',
    slug: 'what-is-science-fair',
    title: 'What is a Science Fair?',
    content: 'A science fair is an exhibition where students display their scientific investigations and projects. Learn what to expect and how to prepare.',
    stage: 'planning',
    category: 'Getting Started',
    author: 'Dr. Sarah Johnson',
    read_time: 5,
    word_count: 850,
    featured: true,
    created_at: '2024-01-01T00:00:00Z',
    updated_at: '2024-01-01T00:00:00Z',
    related_articles: ['scientific-method', 'research-question'],
  },
  {
    id: '2',
    slug: 'scientific-method',
    title: 'The Scientific Method Explained',
    content: 'Understand the steps of the scientific method: observation, hypothesis, experimentation, analysis, and conclusion.',
    stage: 'research',
    category: 'Methodology',
    author: 'Dr. James Chen',
    read_time: 6,
    word_count: 1200,
    featured: true,
    created_at: '2024-01-02T00:00:00Z',
    updated_at: '2024-01-02T00:00:00Z',
    related_articles: ['hypothesis-prediction', 'variables'],
  },
  {
    id: '3',
    slug: 'research-question',
    title: 'How to Ask the Perfect Research Question',
    content: 'Your research question guides your entire project. Learn how to craft a clear, testable, and interesting question.',
    stage: 'planning',
    category: 'Planning',
    author: 'Dr. Maria Rodriguez',
    read_time: 5,
    word_count: 920,
    featured: true,
    created_at: '2024-01-03T00:00:00Z',
    updated_at: '2024-01-03T00:00:00Z',
    related_articles: ['what-is-science-fair', 'scientific-method'],
  },
  {
    id: '4',
    slug: 'hypothesis-prediction',
    title: 'Hypothesis vs. Prediction',
    content: 'Learn the difference between a hypothesis and a prediction, and how each plays a role in the scientific method.',
    stage: 'research',
    category: 'Methodology',
    author: 'Dr. Robert Smith',
    read_time: 4,
    word_count: 750,
    featured: false,
    created_at: '2024-01-04T00:00:00Z',
    updated_at: '2024-01-04T00:00:00Z',
    related_articles: ['scientific-method', 'variables'],
  },
  {
    id: '5',
    slug: 'literature-review',
    title: 'Literature Review: Finding Sources',
    content: 'Discover how to find, evaluate, and organize scientific sources for your project.',
    stage: 'research',
    category: 'Research',
    author: 'Dr. Emily Watson',
    read_time: 7,
    word_count: 1400,
    featured: false,
    created_at: '2024-01-05T00:00:00Z',
    updated_at: '2024-01-05T00:00:00Z',
    related_articles: ['research-question'],
  },
  {
    id: '6',
    slug: 'experiment-design',
    title: 'Designing a Controlled Experiment',
    content: 'Learn how to structure your experiment to test your hypothesis with proper controls and variables.',
    stage: 'design',
    category: 'Methodology',
    author: 'Dr. David Lee',
    read_time: 8,
    word_count: 1600,
    featured: true,
    created_at: '2024-01-06T00:00:00Z',
    updated_at: '2024-01-06T00:00:00Z',
    related_articles: ['variables', 'hypothesis-prediction'],
  },
  {
    id: '7',
    slug: 'variables',
    title: 'Variables Explained',
    content: 'Understand independent, dependent, and controlled variables and how they work in experiments.',
    stage: 'design',
    category: 'Methodology',
    author: 'Dr. Lisa Anderson',
    read_time: 5,
    word_count: 950,
    featured: false,
    created_at: '2024-01-07T00:00:00Z',
    updated_at: '2024-01-07T00:00:00Z',
    related_articles: ['experiment-design', 'scientific-method'],
  },
  {
    id: '8',
    slug: 'lab-safety',
    title: 'Lab Safety 101',
    content: 'Essential safety practices for conducting experiments safely and responsibly.',
    stage: 'execution',
    category: 'Safety',
    author: 'Dr. Michael Brown',
    read_time: 6,
    word_count: 1100,
    featured: true,
    created_at: '2024-01-08T00:00:00Z',
    updated_at: '2024-01-08T00:00:00Z',
    related_articles: ['experiment-design'],
  },
  {
    id: '9',
    slug: 'data-collection',
    title: 'Data Collection Best Practices',
    content: 'Learn how to collect accurate, consistent, and reliable data for your experiment.',
    stage: 'execution',
    category: 'Data',
    author: 'Dr. Jennifer Wilson',
    read_time: 6,
    word_count: 1250,
    featured: false,
    created_at: '2024-01-09T00:00:00Z',
    updated_at: '2024-01-09T00:00:00Z',
    related_articles: ['data-recording', 'variables'],
  },
  {
    id: '10',
    slug: 'data-recording',
    title: 'Recording and Organizing Your Data',
    content: 'Organize your experimental data in a way that makes analysis and presentation easy.',
    stage: 'execution',
    category: 'Data',
    author: 'Dr. Kevin Davis',
    read_time: 5,
    word_count: 890,
    featured: false,
    created_at: '2024-01-10T00:00:00Z',
    updated_at: '2024-01-10T00:00:00Z',
    related_articles: ['data-collection', 'statistics'],
  },
  {
    id: '11',
    slug: 'statistics',
    title: 'Basic Statistics for Science Fairs',
    content: 'Learn statistical concepts and calculations to analyze your data effectively.',
    stage: 'analysis',
    category: 'Analysis',
    author: 'Dr. Amanda Taylor',
    read_time: 7,
    word_count: 1350,
    featured: false,
    created_at: '2024-01-11T00:00:00Z',
    updated_at: '2024-01-11T00:00:00Z',
    related_articles: ['data-recording', 'graphs'],
  },
  {
    id: '12',
    slug: 'graphs',
    title: 'Creating Effective Graphs & Charts',
    content: 'Visualize your data with clear, informative graphs and charts.',
    stage: 'analysis',
    category: 'Presentation',
    author: 'Dr. Christopher Martin',
    read_time: 6,
    word_count: 1100,
    featured: false,
    created_at: '2024-01-12T00:00:00Z',
    updated_at: '2024-01-12T00:00:00Z',
    related_articles: ['statistics', 'poster-design'],
  },
  {
    id: '13',
    slug: 'poster-design',
    title: 'Poster Design 101',
    content: 'Design an eye-catching, informative science fair poster that tells your project story.',
    stage: 'presentation',
    category: 'Presentation',
    author: 'Dr. Patricia White',
    read_time: 6,
    word_count: 1050,
    featured: true,
    created_at: '2024-01-13T00:00:00Z',
    updated_at: '2024-01-13T00:00:00Z',
    related_articles: ['graphs', 'pitch'],
  },
  {
    id: '14',
    slug: 'pitch',
    title: 'The 60-Second Pitch',
    content: 'Master the art of explaining your project in 60 seconds or less to judges and audience members.',
    stage: 'presentation',
    category: 'Presentation',
    author: 'Dr. Nathan Green',
    read_time: 5,
    word_count: 920,
    featured: true,
    created_at: '2024-01-14T00:00:00Z',
    updated_at: '2024-01-14T00:00:00Z',
    related_articles: ['poster-design', 'judge-questions'],
  },
  {
    id: '15',
    slug: 'judge-questions',
    title: 'Answering Judge Questions Like a Pro',
    content: 'Prepare for and answer tough questions from judges with confidence and clarity.',
    stage: 'presentation',
    category: 'Presentation',
    author: 'Dr. Susan Black',
    read_time: 5,
    word_count: 850,
    featured: false,
    created_at: '2024-01-15T00:00:00Z',
    updated_at: '2024-01-15T00:00:00Z',
    related_articles: ['pitch', 'poster-design'],
  },
]

export function getArticles(): Article[] {
  return articles
}

export function getArticleBySlug(slug: string): Article | undefined {
  return articles.find(article => article.slug === slug)
}

export function getFeaturedArticles(): Article[] {
  return articles.filter(article => article.featured)
}

export function getArticlesByStage(stage: Article['stage']): Article[] {
  return articles.filter(article => article.stage === stage)
}

export function getArticlesByCategory(category: string): Article[] {
  return articles.filter(article => article.category === category)
}

export function searchArticles(query: string): Article[] {
  const lowerQuery = query.toLowerCase()
  return articles.filter(
    article =>
      article.title.toLowerCase().includes(lowerQuery) ||
      article.content.toLowerCase().includes(lowerQuery) ||
      article.category.toLowerCase().includes(lowerQuery)
  )
}
