import { Stage } from '@/types'

export const stages: Stage[] = [
  {
    id: '1',
    name: 'Chapter 0-1: Before You Begin & Getting Started',
    description: 'Build the right foundation for your research journey. Learn what research truly involves, develop the mindset of a successful researcher, understand the competition pathway from local to ISEF, and discover what makes projects competitive.',
    timeline: '2-4 weeks',
    checklist_items: [
      'Develop a growth mindset focused on learning, not just awards',
      'Understand the multi-tiered competition pathway',
      'Learn about eligibility requirements (grades 9-12, age limit, project limits)',
      'Familiarize yourself with the ISEF competition structure',
      'Identify what skills and benefits you want from science fair',
      'Commit to embracing failure, rejection, and iteration',
    ],
    tips: [
      'Remember that you don\'t have to be a genius—you need the right mindset',
      'View science fairs as a beginning, not an ending for your project',
      'Focus on growth and genuine interest in your topic',
      'Understand that competition pushes you to continuously improve',
      'Build your network early by connecting with other researchers',
    ],
    common_mistakes: [
      'Focusing only on winning awards rather than learning',
      'Giving up after the first rejection or setback',
      'Underestimating the value of failure in research',
      'Not understanding the competition timeline and requirements',
      'Choosing a topic just to win, rather than what genuinely interests you',
    ],
    created_at: '2024-01-01T00:00:00Z',
  },
  {
    id: '2',
    name: 'Chapter 2: Finding Your Idea',
    description: 'Uncover ideas worth pursuing by exploring six sources of inspiration, evaluating your ideas against six critical criteria, reading and understanding scientific literature, conducting a thorough literature review, and using modern research tools.',
    timeline: '3-4 weeks',
    checklist_items: [
      'Explore the six sources: surroundings, current events, your passions, other people, reading, and past research',
      'Identify at least 3-5 potential research ideas',
      'Evaluate each idea against: interest, originality, feasibility, measurability, impact, ethicality',
      'Conduct a preliminary literature review using key resources',
      'Map existing research using Connected Papers or ResearchRabbit',
      'Identify research gaps that your project could address',
      'Narrow down to your final research question',
      'Document your idea sources and the evolution of your question',
    ],
    tips: [
      'Good ideas combine observations, staying informed, asking questions, and exploring existing research',
      'The best research questions come from genuinely asking "what if?"',
      'Read papers strategically: abstract first, conclusion second, methods/results only if replicating',
      'Group papers by theme rather than treating each as isolated',
      'Use visualization tools like Connected Papers to spot underexplored niches',
      'Don\'t limit yourself to ideas that immediately seem feasible—brainstorm broadly first',
    ],
    common_mistakes: [
      'Choosing ideas that are too broad to complete in one year',
      'Only reading papers that support your idea instead of all perspectives',
      'Confusing an important problem with an unexplored research gap',
      'Not narrowing down your scope enough before starting',
      'Ignoring conflicting research results when they often reveal best questions',
    ],
    created_at: '2024-01-02T00:00:00Z',
  },
  {
    id: '3',
    name: 'Chapter 3: Designing Your Research',
    description: 'Create a solid experimental plan by crafting a focused research question, selecting the right methodology, finding mentorship, and formulating a detailed research plan that meets ISEF requirements.',
    timeline: '4-6 weeks',
    checklist_items: [
      'Refine your research question to be: focused, complex, arguable, and researchable',
      'Identify your independent, dependent, and controlled variables',
      'Choose your methodology: experimental, engineering, computer science, theoretical, observational, behavioral, meta-analysis, simulation, or product testing',
      'Identify and contact potential mentors (aim for 20-30 outreach emails)',
      'Write your complete research plan including all required sections',
      'For human subjects: plan consent process and describe safety measures',
      'For animal research: justify necessity and describe care protocols',
      'For hazardous materials: document risk assessments and disposal methods',
      'Have your research plan reviewed by a mentor or teacher',
      'Get IRB/SRC approval if required for your project type',
    ],
    tips: [
      'Make your research question narrow and specific enough to answer in one year',
      'Good research questions require investigation, not a quick search',
      'Don\'t be discouraged if mentors don\'t respond immediately—keep trying',
      'Email mentors with specific questions, not just "will you mentor me?"',
      'Your research plan is a roadmap; small deviations are normal',
      'Include more detail than you think necessary—it helps you stay organized',
    ],
    common_mistakes: [
      'Choosing research questions that are too broad or too simple',
      'Forgetting to include safety precautions in your plan',
      'Not identifying variables clearly enough',
      'Assuming you can find a mentor quickly—persistence is key',
      'Underestimating how much time the planning phase takes',
    ],
    created_at: '2024-01-03T00:00:00Z',
  },
  {
    id: '4',
    name: 'Chapter 4: Conducting Your Research',
    description: 'Execute your research systematically by maintaining detailed lab notebooks, staying organized, troubleshooting problems creatively, and adapting when obstacles arise while maintaining scientific rigor.',
    timeline: '8-16 weeks',
    checklist_items: [
      'Set up your lab notebook with clear date, project title, objective for each entry',
      'Record procedures in enough detail for replication',
      'Document all observations, including unexpected events',
      'Enter raw data consistently using same units and formatting',
      'Outline next steps at end of each session',
      'Conduct multiple trials (aim for 3+ repetitions minimum)',
      'Maintain organized digital and physical records',
      'Take photos/videos of key experimental moments',
      'Track any deviations from original research plan',
      'Document any equipment issues or contamination',
      'Identify when results support or contradict your hypothesis',
    ],
    tips: [
      'Record data in real-time, not from memory',
      'Keep detailed notes even when experiments fail—these are your most important data',
      'Use consistent units and formatting for all measurements',
      'Document environmental factors that might affect results',
      'Take photos of your setup and results',
      'If an experiment fails, that\'s data; record exactly what went wrong',
      'More trials = stronger data; prioritize quality over quantity',
    ],
    common_mistakes: [
      'Changing procedures mid-experiment instead of noting as new trial',
      'Not recording enough data points for statistical analysis',
      'Forgetting to note environmental conditions affecting results',
      'Performing too few trials',
      'Relying on memory instead of immediate documentation',
    ],
    created_at: '2024-01-04T00:00:00Z',
  },
  {
    id: '5',
    name: 'Chapter 5: Communicating Your Project',
    description: 'Present your research professionally by writing a clear research paper and designing an engaging poster that communicate your findings effectively to judges and audiences.',
    timeline: '3-4 weeks',
    checklist_items: [
      'Write your research paper with all standard sections: abstract, introduction, methods, results, discussion, conclusion, references',
      'Ensure your abstract (150-200 words) summarizes the entire project',
      'Organize paper logically and use consistent formatting',
      'Cite all sources in proper format (APA, MLA, or Chicago)',
      'Have your paper proofread for grammar and clarity',
      'Plan your poster message in one sentence',
      'Look at successful poster examples for inspiration',
      'Organize poster sections in logical flow (top-left to bottom-right)',
      'Design for readability: appropriate font sizes and high contrast',
      'Use graphs, charts, photos instead of text-heavy paragraphs',
      'Verify poster size is within competition limits',
      'Double-check all spelling, grammar, and figure labels',
      'Print and review before final submission',
    ],
    tips: [
      'Write your abstract last after you\'ve finished your paper',
      'Use data to support claims; let your results speak',
      'Be objective and avoid personal opinions in your writing',
      'Follow all formatting guidelines specified by your competition',
      'Visit successful poster examples from previous ISEF competitions',
      'Use 2-3 main colors consistently throughout your poster',
      'Make flow clear with arrows or numbering',
      'Avoid technical jargon or explain all acronyms clearly',
      'Every figure should maintain your main message',
    ],
    common_mistakes: [
      'Overcrowding the poster with too much text',
      'Using unclear or poorly labeled figures',
      'Forgetting to include your research question or conclusion',
      'Poor spelling or grammar in final paper',
      'Creating a poster that\'s hard to follow or read from a distance',
    ],
    created_at: '2024-01-05T00:00:00Z',
  },
  {
    id: '6',
    name: 'Chapter 6: Beyond the Fair',
    description: 'Continue your research journey beyond competition day by networking with researchers, publishing your findings, building on your work, and making real-world impact with your discoveries.',
    timeline: 'Ongoing',
    checklist_items: [
      'Maintain connections with mentors and researchers you met',
      'Explore opportunities to publish your research',
      'Consider submitting to additional competitions beyond ISEF',
      'Identify ways your research could continue or expand',
      'Seek internship or research opportunities in your field',
      'Present your work at professional conferences if possible',
      'Update your portfolio with your research accomplishments',
      'Reflect on lessons learned from your research journey',
      'Mentor other students beginning their research',
      'Stay engaged with the scientific community',
    ],
    tips: [
      'Stay curious—science fair is a beginning, not an ending',
      'Your research has real value; look for ways to share it further',
      'The people you meet at science fairs are often lifetime colleagues',
      'Publishing gives your work lasting impact and builds your resume',
      'Consider how your research connects to larger problems you care about',
      'Use your research experience to open doors to internships and scholarships',
    ],
    common_mistakes: [
      'Stopping your work immediately after the fair ends',
      'Losing touch with mentors and the research community',
      'Not documenting your work for future publication',
      'Missing opportunities to continue or expand your research',
      'Underestimating the long-term value of your research experience',
    ],
    created_at: '2024-01-06T00:00:00Z',
  },
]

export function getStages(): Stage[] {
  return stages
}

export function getStageByName(name: string): Stage | undefined {
  return stages.find(stage => stage.name === name)
}

export function getAllStageNames(): string[] {
  return stages.map(stage => stage.name)
}
